[package]

name = "ui-toolkit"
description = "AvdanOS UI Toolkit"
documentation = "https://docs.avdanos.com/"
homepage = "https://avdanos.com/"
license = "GPL-3.0"
version = "0.0.1"
author = "Akane <zenailsc@gmail.com>"
edition = "2021"

[dependencies]

iced = "0.9.0"
